"""default products created

Revision ID: 0450e1ef9a67
Revises: 9896355c9bd7
Create Date: 2024-01-25 22:19:18.401614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0450e1ef9a67'
down_revision = '9896355c9bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('quantity_to_export',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('exported_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('exported_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity_to_export',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
