"""native_country added to Product

Revision ID: 9896355c9bd7
Revises: e5e70ca11c74
Create Date: 2024-01-25 21:07:43.847610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9896355c9bd7'
down_revision = 'e5e70ca11c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('native_country', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('native_country')

    # ### end Alembic commands ###
